# Data Frames

Combining mulitple Series called as Dataframes

In [1]:
import numpy as np
import pandas as pd

### Creating a DataFrames

In [2]:
data={
    'Name':['Neha','Rahul','Sachin','Supriya'],
    'Age':[21,30 ,29, 42],
    'City':['Mumbai','Lucknow','Varanasi','Delhi'],
    'Salary':[40000,70000,64000,85000]
}

In [3]:
df=pd.DataFrame(data)
df

      Name  Age      City  Salary
0     Neha   21    Mumbai   40000
1    Rahul   30   Lucknow   70000
2   Sachin   29  Varanasi   64000
3  Supriya   42     Delhi   85000

In [4]:
list=[
    ['Jigar',28,'Bangalore',65000],
    ['Anamika', 30,'Karnataka', 70000],
    ['Himanshu', 24,'Pune',45000],
    ['Harshada',45,'Kolkata',85000]
]

cols=['Name','Age','City','Salary']
df2=pd.DataFrame(list,columns=cols)

In [5]:
df2

       Name  Age       City  Salary
0     Jigar   28  Bangalore   65000
1   Anamika   30  Karnataka   70000
2  Himanshu   24       Pune   45000
3  Harshada   45    Kolkata   85000

### Selection and Indexing of Columns

In [7]:
df2['Name']

0       Jigar
1     Anamika
2    Himanshu
3    Harshada
Name: Name, dtype: object

In [8]:
df2['City']

0    Bangalore
1    Karnataka
2         Pune
3      Kolkata
Name: City, dtype: object

In [9]:
#  To select multiple columns give list of columns as input
df2[['Name','Age','City']]

       Name  Age       City
0     Jigar   28  Bangalore
1   Anamika   30  Karnataka
2  Himanshu   24       Pune
3  Harshada   45    Kolkata

### Creating a new column

In [10]:
# To add a column
df2['Designation']=['Data Analyst', 'Data Scientist','Business Analyst', 'Quality Analyst']
df2

       Name  Age       City  Salary       Designation
0     Jigar   28  Bangalore   65000      Data Analyst
1   Anamika   30  Karnataka   70000    Data Scientist
2  Himanshu   24       Pune   45000  Business Analyst
3  Harshada   45    Kolkata   85000   Quality Analyst

### Removing Columns

In [11]:
# Removing a Column
# df2.drop('Designation',axis=0)
df2.drop('Designation',axis=1)

# Axis 0 is Horizontal to access Rows
# Axis 1 is Vertical to access Columns

#  Never removes from main data just you can view the snapshot how the data will look after removing it

       Name  Age       City  Salary
0     Jigar   28  Bangalore   65000
1   Anamika   30  Karnataka   70000
2  Himanshu   24       Pune   45000
3  Harshada   45    Kolkata   85000

In [12]:
df2

       Name  Age       City  Salary       Designation
0     Jigar   28  Bangalore   65000      Data Analyst
1   Anamika   30  Karnataka   70000    Data Scientist
2  Himanshu   24       Pune   45000  Business Analyst
3  Harshada   45    Kolkata   85000   Quality Analyst

In [13]:
# to remove specific one
df2.drop('Designation', axis=1, inplace=True)

# inplace states that the data is to be removed permanently (Boolean Value to be given by default it is false)

In [14]:
df2
#  Now the Designation is permanently removed

       Name  Age       City  Salary
0     Jigar   28  Bangalore   65000
1   Anamika   30  Karnataka   70000
2  Himanshu   24       Pune   45000
3  Harshada   45    Kolkata   85000

In [15]:
df2.drop(['City','Age'],axis=1)

       Name  Salary
0     Jigar   65000
1   Anamika   70000
2  Himanshu   45000
3  Harshada   85000

In [16]:
df2.drop(0,axis=0)
# Drops first row

       Name  Age       City  Salary
1   Anamika   30  Karnataka   70000
2  Himanshu   24       Pune   45000
3  Harshada   45    Kolkata   85000

## Row

In [17]:
df2

       Name  Age       City  Salary
0     Jigar   28  Bangalore   65000
1   Anamika   30  Karnataka   70000
2  Himanshu   24       Pune   45000
3  Harshada   45    Kolkata   85000

In [21]:
df2.loc[0]

Name          Jigar
Age              28
City      Bangalore
Salary        65000
Name: 0, dtype: object

In [19]:
df2.loc[[0,1]]
# loc is used to select the rows

      Name  Age       City  Salary
0    Jigar   28  Bangalore   65000
1  Anamika   30  Karnataka   70000

In [27]:
df2.iloc[[1,2]]

       Name  Age       City  Salary
1   Anamika   30  Karnataka   70000
2  Himanshu   24       Pune   45000

### Selecting subsets of Rows and Columns

In [24]:
df.loc[[0,1]][["City","Salary"]]

      City  Salary
0   Mumbai   40000
1  Lucknow   70000

In [28]:
df.loc[[2,3]][["Name",'Age']]

      Name  Age
2   Sachin   29
3  Supriya   42

### Conditional Selections

In [29]:
df

      Name  Age      City  Salary
0     Neha   21    Mumbai   40000
1    Rahul   30   Lucknow   70000
2   Sachin   29  Varanasi   64000
3  Supriya   42     Delhi   85000

In [32]:
# Age is above 30
df[df['Age']>30]

      Name  Age   City  Salary
3  Supriya   42  Delhi   85000

In [35]:
df[(df['Age']>30)& (df['City']=='Delhi')]

      Name  Age   City  Salary
3  Supriya   42  Delhi   85000