# Group By

done categorically

Qualitative Data:
- Nominal Data: Categorical ( movie genre, eye color, brands)
- Ordinal Data: Ranking of Data ( poor, good, bad)

Quantitative Data:
- Continuous Data (1.23, 1.24, 1.25)
- Discrete Data (1, 2, 3, 4)

In [1]:
import numpy as np
import pandas as pd

In [3]:
data={
    'Category':['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store':['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity':[10, 15, 12, 18, 8, 20, 15, 25],
    'Date':pd.date_range('2023-01-01', periods=8)
}

In [4]:
df=pd.DataFrame(data)

In [17]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [18]:
# Group by Category and calculate the sum of sales
df.groupby('Category')

In [6]:
d2=df.groupby('Category')
d2
for i, j in d2:
    print(i)
    print(j)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [19]:
obj=df.groupby('Category')['Sales'].sum()
obj

Category
A    570
B    930
Name: Sales, dtype: int64

In [20]:
# Group by Store and calculate the sum of Sales
obj2=df.groupby('Store')['Sales'].sum()
obj2

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [21]:
#  Group by multiple columns
#  Group by Category and stores
obj1=df.groupby(['Category','Store'])['Sales'].sum()
obj1

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

### Aggregation Functions

Combining multiple things to get the answers
- Mean
- Median
- Standard Deviation
- Variance

In [9]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [10]:
df['Sales'].mean()

# mean, meadian, min, max, std, count, variance

187.5

In [27]:
df['Sales'].agg(['mean','median','max', 'min', 'count', 'std'])

mean      187.500000
median    190.000000
max       300.000000
min       100.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64