In [2]:
import numpy as np
import pandas as pd

### Merging Joining and Concatenation

In [3]:
employees=pd.DataFrame({
    'emp_id':[1, 2, 3, 4, 5],
    'emp_name':['Harshal', 'Kishor', 'Sangam', 'Anand', 'Pooja'],
    'emp_dept':['HR','IT','finance','IT','HR']
})

salaries=pd.DataFrame({
    'emp_id':[1, 2, 3, 6, 7],
    'salary':[50000, 75000, 62000, 70000, 80000],
    'bonus':[4000, 9000, 7000, 7000, 12000]
})

In [4]:
employees

   emp_id emp_name emp_dept
0       1  Harshal       HR
1       2   Kishor       IT
2       3   Sangam  finance
3       4    Anand       IT
4       5    Pooja       HR

In [7]:
salaries

   emp_id  salary  bonus
0       1   50000   4000
1       2   75000   9000
2       3   62000   7000
3       6   70000   7000
4       7   80000  12000

In [9]:
pd.merge(employees,salaries,on='emp_id')

   emp_id emp_name emp_dept  salary  bonus
0       1  Harshal       HR   50000   4000
1       2   Kishor       IT   75000   9000
2       3   Sangam  finance   62000   7000

In [10]:
pd.merge(employees,salaries,on='emp_id',how='inner')

   emp_id emp_name emp_dept  salary  bonus
0       1  Harshal       HR   50000   4000
1       2   Kishor       IT   75000   9000
2       3   Sangam  finance   62000   7000

In [11]:
pd.merge(employees,salaries,on='emp_id',how='outer')

   emp_id emp_name emp_dept   salary    bonus
0       1  Harshal       HR  50000.0   4000.0
1       2   Kishor       IT  75000.0   9000.0
2       3   Sangam  finance  62000.0   7000.0
3       4    Anand       IT      NaN      NaN
4       5    Pooja       HR      NaN      NaN
5       6      NaN      NaN  70000.0   7000.0
6       7      NaN      NaN  80000.0  12000.0

In [12]:
pd.merge(employees,salaries,on='emp_id',how='left')

   emp_id emp_name emp_dept   salary   bonus
0       1  Harshal       HR  50000.0  4000.0
1       2   Kishor       IT  75000.0  9000.0
2       3   Sangam  finance  62000.0  7000.0
3       4    Anand       IT      NaN     NaN
4       5    Pooja       HR      NaN     NaN

In [13]:
pd.merge(employees,salaries,on='emp_id',how='right')

   emp_id emp_name emp_dept  salary  bonus
0       1  Harshal       HR   50000   4000
1       2   Kishor       IT   75000   9000
2       3   Sangam  finance   62000   7000
3       6      NaN      NaN   70000   7000
4       7      NaN      NaN   80000  12000

### Concatenation of dataframes

In [14]:
df1=pd.DataFrame({
    'A':['A0', 'A1', 'A2'],
    'B':['B0', 'B1', 'B2'],
    'C':['C0', 'C1', 'C2']
})

df2=pd.DataFrame({
    'A':['A3', 'A4', 'A5'],
    'B':['B3', 'B4', 'B5'],
    'C':['C3', 'C4', 'C5']
})

In [16]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [17]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [18]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [19]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [21]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joining two dataframes**

In [4]:
df1=pd.DataFrame({
    'name':['Prerana', 'Rucheeta', 'Palak', 'Sid']
},index=[1,2,3,4])

df2=pd.DataFrame({
    'score':[89, 90, 75, 98]
}, index=[2,3,4,5])

In [5]:
df1

       name
1   Prerana
2  Rucheeta
3     Palak
4       Sid

In [6]:
df2

   score
2     89
3     90
4     75
5     98

In [7]:
df1.join(df2)

       name  score
1   Prerana    NaN
2  Rucheeta   89.0
3     Palak   90.0
4       Sid   75.0

In [8]:
df2.join(df1)

   score      name
2     89  Rucheeta
3     90     Palak
4     75       Sid
5     98       NaN

In [9]:
df1.join(df2,how='outer')

       name  score
1   Prerana    NaN
2  Rucheeta   89.0
3     Palak   90.0
4       Sid   75.0
5       NaN   98.0