In [1]:
import numpy as np
import pandas as pd

#### Finding Missing Data

In [2]:
data={
    'A':[1,2, np.nan,4,5],
    'B':[1,2,3,4, 5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[np.nan,2,np.nan,np.nan,5]
}

In [3]:
df=pd.DataFrame(data)
df
# nan is Not A Number

     A  B    C    D
0  1.0  1  1.0  NaN
1  2.0  2  2.0  2.0
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [19]:
df.isnull()
# Check if data is null or not

       A      B      C      D
0  False  False  False   True
1  False  False  False  False
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [20]:
df.isnull().sum()
# Count the nulls data

A    1
B    0
C    2
D    3
dtype: int64

In [21]:
df.isna()

       A      B      C      D
0  False  False  False   True
1  False  False  False  False
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [22]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [23]:
df.isna().any()
# Checking which columns have the null values

A     True
B    False
C     True
D     True
dtype: bool

Removing Missing data

In [43]:
df.dropna()
# Removes all rows having single null data

# Dropna works row wise

     A  B    C    D
1  2.0  2  2.0  2.0

In [33]:
df

     A  B    C    D
0  1.0  1  1.0  NaN
1  2.0  2  2.0  2.0
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [36]:
df.dropna(thresh=3)
#  threshhold = have same number of non null values

     A  B    C    D
0  1.0  1  1.0  NaN
1  2.0  2  2.0  2.0
4  5.0  5  NaN  5.0

In [37]:
df.dropna(thresh=4)

     A  B    C    D
1  2.0  2  2.0  2.0

#### Filling the Missing Data

In [40]:
df

     A  B    C    D
0  1.0  1  1.0  NaN
1  2.0  2  2.0  2.0
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [44]:
df.fillna(0)

# fillna works column wise

     A  B    C    D
0  1.0  1  1.0  0.0
1  2.0  2  2.0  2.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [4]:
values={
    'A':0,
    'B':100,
    'C':200,
    'D':300
}

df.fillna(values)

     A  B      C      D
0  1.0  1    1.0  300.0
1  2.0  2    2.0    2.0
2  0.0  3    3.0  300.0
3  4.0  4  200.0  300.0
4  5.0  5  200.0    5.0

In [5]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  3.5
1  2.0  2  2.0  2.0
2  3.0  3  3.0  3.5
3  4.0  4  2.0  3.5
4  5.0  5  2.0  5.0