### Operations in Pandas

Mean, median, mode, sum, count, etc all these are operations we will discussing it here more in detail

Basic Preprocessing of data

In [1]:
import numpy as np
import pandas as pd

**Data Frames Basic Operation**

In [19]:
df=pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B':[10, 20, 30, 40, 50],
    'C':[100, 200, 300, 400, 500]
})

df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

Dataframes Applying Functions

In [5]:
df.shape

(5, 3)

In [6]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [8]:
df.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [9]:
df['A']+=10

In [10]:
df

    A   B    C
0  11  10  100
1  12  20  200
2  13  30  300
3  14  40  400
4  15  50  500

**Applying functions to dataframes**

In [11]:
df

    A   B    C
0  11  10  100
1  12  20  200
2  13  30  300
3  14  40  400
4  15  50  500

In [20]:
def square(x):
    return x**2

In [21]:
df['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [22]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [23]:
df['D']=df['B'].apply(square)

In [24]:
df

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [25]:
#  Using lambda funcrtions

df['E']=df['A'].apply(lambda x:x**4)

In [26]:
df

   A   B    C     D    E
0  1  10  100   100    1
1  2  20  200   400   16
2  3  30  300   900   81
3  4  40  400  1600  256
4  5  50  500  2500  625

Feature Extraction

Pandas support below files
1. csv => pd.read_csv('file.csv')
2. excel => pd.read_excel('file.xlsx')
3. json => pd.read_json('file.json')
4. text => pd.read_csv('file.txt', delimiter=' ')
5. tsv => pd.read_tsv('file.tsv', sep='/t')
6. html tables => pd.html('file.html')
7. sql databases => pd.read_sql(query,connection)
8. parquet => pd.read_parquet('file.parquet')
9. feather => pd.read_feather('file.feather')
10. pickle => pd.read_pickle('file.pkl')
11. hdf5 (Hierarchial data format) => pd.read_hdf('file.h5')
12. orc (Optimizezd Row Columnar) => pandas.read_orc()
13. google sheets => use gpread, pandas+API